# Generated by Django 5.1.6 on 2025-03-27 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='index_product_details',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_highlights', models.TextField(blank=True, null=True)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('product_categorys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_category')),
            ],
        ),
    ]
