# Generated by Django 5.1.6 on 2025-03-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index_product_details',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('product_description', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='index_product_details/')),
            ],
        ),
    ]
