# Generated by Django 5.1.6 on 2025-03-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_product_details',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('home_furniture', 'Home & Furniture'), ('appliances', 'Appliances')], default='shoes', max_length=20),
        ),
        migrations.AlterField(
            model_name='index_product_details',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
