# Generated by Django 5.1.6 on 2025-03-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_product_details',
            name='product_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='index_product_details',
            name='product_size_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
