# Generated by Django 5.1.6 on 2025-03-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_index_product_details_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_product_details',
            name='category',
        ),
    ]
