# Generated by Django 5.1.6 on 2025-03-26 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_index_product_details_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('category', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='index_product_details',
            name='product_categorys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_category'),
        ),
    ]
