# Generated by Django 5.2.3 on 2025-06-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index_product_details',
            old_name='product_categorys',
            new_name='product_category',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='description',
        ),
        migrations.AddField(
            model_name='product_category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
