# Generated by Django 5.2.3 on 2025-07-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_product_categorys_index_product_details_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_product_details',
            name='banner_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
