# Generated by Django 5.2.3 on 2025-07-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_index_product_details_banner_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_product_details',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
