# Generated by Django 5.2.3 on 2025-07-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_index_product_details_is_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index_product_details',
            options={'ordering': ['display_order', 'product_name']},
        ),
        migrations.AlterModelOptions(
            name='product_category',
            options={'ordering': ['order_number', 'name']},
        ),
        migrations.AddField(
            model_name='index_product_details',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_category',
            name='order_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
