# Generated by Django 5.1.6 on 2025-04-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_re_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='re_password',
        ),
    ]
