# Generated by Django 5.1.6 on 2025-03-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_index_product_details_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_product_details',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
