# Generated by Django 5.1.6 on 2025-03-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_index_product_details_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index_product_details',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
